name: CD

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
  build:
    uses: ./.github/workflows/build.yaml
  check:
    uses: ./.github/workflows/check.yaml
  test:
    uses: ./.github/workflows/test.yaml
  publish:
    uses: ./.github/workflows/publish.yaml
    secrets: inherit