name: CI

on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:    
      - 'master'

jobs:
  setup:
    uses: ./.github/workflows/build.yml
  check:
    uses: ./.github/workflows/build.yml
  test:
    uses: ./.github/workflows/test.yml
  build:
    uses: ./.github/workflows/check.yml